version: '3.1'
services:
  localstack:
    container_name: "localstack"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "4566-4583:4566-4583"
    environment:
      - LAMBDA_EXECUTOR=docker_reuse
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - DEBUG=1
      - PORT_WEB_UI=8080
    volumes:
      - "/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
